version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:80"
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - APP_KEY=base64:your_app_key_here
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_DATABASE=herca_db
      - DB_USERNAME=herca_user
      - DB_PASSWORD=herca_password
    depends_on:
      - db
    networks:
      - herca-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=herca_db
      - MYSQL_USER=herca_user
      - MYSQL_PASSWORD=herca_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - herca-network

  nginx:
    image: nginx:alpine
    ports:
      - "3004:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html/public
    depends_on:
      - app
    networks:
      - herca-network

volumes:
  db_data:

networks:
  herca-network:
    driver: bridge