version: '3.8'

services:
  app:
    build: .
    container_name: herca-be
    restart: unless-stopped
    ports:
      - "3004:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=herca
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: herca-db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: herca
