version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: herca-laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - herca-network
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=herca_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  nginx:
    image: nginx:stable-alpine
    container_name: herca-nginx
    restart: unless-stopped
    ports:
      - "3002:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - herca-network
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: herca-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: herca_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - herca-network

volumes:
  mysql-data:

networks:
  herca-network:
    driver: bridge