version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: herca-laravel
    container_name: herca-be-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - herca-network
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: herca_db
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "9000:9000"

  webserver:
    image: nginx:alpine
    container_name: herca-be-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - herca-network

  db:
    image: mysql:8.0
    container_name: herca-be-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: herca_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - herca-network

networks:
  herca-network:

volumes:
  db_data:
