version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: herca-laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - herca-network
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=herca_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    expose:
      - "9000" # hanya expose internal, karena Nginx host yang akan mengakses

  mysql:
    image: mysql:8
    container_name: herca-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: herca_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - herca-network

volumes:
  mysql-data:

networks:
  herca-network:
    driver: bridge
